### ISSUE TITLE
Upload to addons.mozilla.org

### ISSUE THREAD

**Issue by flying-sheep** [livereload/livereload-extensions#33]
there’s no reason why [the AMO version](https://addons.mozilla.org/de/firefox/addon/livereload/) shouldn’t be kept up to date.

**Comment by jnachtigall** [comment]
Especially since with FF 43 the manually installed addon is blocked since being not signed. Sigh, can you please upload to AMO as you did also for Chrome.

**Comment by jnachtigall** [comment]
Oops, sorry, I just noticed that the current version (2.1.1) is already at AMO. So I think this issue could be closed.

**Comment by flying-sheep** [comment]
oh, good!
