### ISSUE TITLE
Unable to build the extensions

### ISSUE THREAD

**Issue by tapthaker** [livereload/livereload-extensions#34]
Trying to build using "grunt all" but getting the following error:

> > Error: Cannot find module 'livereload-js' from '/Users/[user]/github/livereload-extensions/src'

I did a npm install before getting started. Am I missing something ??

**Comment by andreyvit** [comment]
Hey! That's a great question; can you please retry `npm install` (perhaps after deleting node_modules subfolder)? There used to be a problem with the previous published version of livereload-js module.
